elements:
  - name: Current Date & Time
    type: text
    parameters:
      pos_x: 20
      pos_y: 80
      width: 1880
      height: 170
      size: 90
#      bounding_box_pos_x: 20
#      bounding_box_pos_y: 870
#      bounding_box_width: 1880
#      text: "\"Saturday April 09 [2022-04-09] - 17:23\""  # +%A %B %d [%G-%m-%d] - %H:%M
      text: "text_lines_from_file(0,1,\"today.txt\")"
      font: ../data/fonts/FiraCode-Medium.ttf
      color: "0xffffffff"
      glow_color: "0xffd06040"
      glow_size: 5


  - name: Calendar
    type: text
    parameters:
      pos_x: 20
      pos_y: 180
      width: 1880
      height: 800
      size: 100
#      bounding_box_pos_x: 20
#      bounding_box_pos_y: 870
#      bounding_box_width: 1880
#      text: "\"Saturday April 09 [2022-04-09] - 17:23\""  # +%A %B %d [%G-%m-%d] - %H:%M
      text: "text_lines_from_file(1,7,\"cal.txt\")"
      font: ../data/fonts/FiraCode-Medium.ttf
      color: "0xffffffff"

  - name: Next
    type: text
    parameters:
      pos_x: 1080
      pos_y: 220
      width: 820
      height: 800
      size: 50
#      bounding_box_pos_x: 20
#      bounding_box_pos_y: 870
#      bounding_box_width: 1880
#      bounding_box_height: 800
#      text: "\"Saturday April 09 [2022-04-09] - 17:23\""  # +%A %B %d [%G-%m-%d] - %H:%M
      text: "text_lines_from_file(0,3,\"next.txt\")"
      font: ../data/fonts/FiraCode-Medium.ttf
      color: "0xffffffff"

  - name: Todo
    type: text
    parameters:
      pos_x: 1080
      pos_y: 420
      width: 820
      height: 800
      size: 50
#      bounding_box_pos_x: 20
#      bounding_box_pos_y: 870
#      bounding_box_width: 1880
#      bounding_box_height: 800
#      text: "\"Saturday April 09 [2022-04-09] - 17:23\""  # +%A %B %d [%G-%m-%d] - %H:%M
      text: "text_lines_from_file(0,0,\"todo.md\")"
      font: ../data/fonts/FiraCode-Medium.ttf
      color: "0xffffffff"
