default_page: 0
elements:
  - name: Soundbank
    type: soundbank
    parameters:
      soundbank_file: "multi_page.omsb"
  - name: Main Stripe Top
    type: block
    parameters:
      pos_x: 0
      pos_y: 200
      width: 1980
      height: 100
      color: 0xff808080
  - name: Main Stripe Bottom
    type: block
    parameters:
      pos_x: 0
      pos_y: 780
      width: 1980
      height: 100
      color: 0xff808080
  - name: Main Page Top Text
    type: text
    parameters:
      pos_x: 20
      pos_y: 200
      width: 1980
      height: 100
      size: 80
      bounding_box_pos_x: 20
      bounding_box_pos_y: 200
      bounding_box_width: 1980
      text: "\"Change Page with Cursor Left + Right\""
      font: ../data/fonts/FiraCode-Medium.ttf
      color: "0xffffffff"
  - name: Main Page Bottom Text
    type: text
    parameters:
      pos_x: 20
      pos_y: 770
      width: 1980
      height: 100
      size: 80
      bounding_box_pos_x: 20
      bounding_box_pos_y: 770
      bounding_box_width: 1980
      text: "$cheval_active_page_number"
      font: ../data/fonts/FiraCode-Medium.ttf
      color: "0xffffffff"
pages:
  - name: Page 0
    elements:
    - name: Page 0 Stripe
      type: block
      parameters:
        pos_x: 0
        pos_y: 490
        width: 1980
        height: 100
        color: 0xff202080
    - name: Page 0 Text
      type: text
      parameters:
        pos_x: 20
        pos_y: 490
        width: 1980
        height: 100
        size: 80
        bounding_box_pos_x: 20
        bounding_box_pos_y: 490
        bounding_box_width: 1980
        text: "\"Page 0\""
        font: ../data/fonts/FiraCode-Medium.ttf
        color: "0xffffffff"

  - name: Page 1
    parameters:
      sound_on_show: PAGE_1_ACTIVATED
    elements:
#    - name: Sound
#      type: sound
#      id: PAGE_1_ACTIVATED
    - name: Page 1 Stripe
      type: block
      parameters:
        pos_x: 0
        pos_y: 490
        width: 1980
        height: 100
        color: 0xff208000
    - name: Page 1 Text
      type: text
      parameters:
        pos_x: 20
        pos_y: 490
        width: 1980
        height: 100
        size: 80
        bounding_box_pos_x: 20
        bounding_box_pos_y: 490
        bounding_box_width: 1980
        text: "\"Page 1\""
        font: ../data/fonts/FiraCode-Medium.ttf
        color: "0xffffffff"
