elements:
  - name: Simple Text
    type: text
    parameters:
      pos_x: 20
      pos_y: 870
      width: 960
      height: 100
      size: 90
      bounding_box_pos_x: 20
      bounding_box_pos_y: 870
      bounding_box_width: 1880
      text: "\"Rust Streamers Forever!\""
      font: ../data/fonts/FiraCode-Medium.ttf
      color: "pink"
#      color: "0xffffffff"
